name: ModDutyDutch
main: com.github.cmptrzd1592.ModDutyDutch.ModDutyDutch
version: 1.0

commands:
    modduty:
        description: announces that the user is currently doing modreqs
        usage: /<command>
        permission: moddutydutch.modduty
        permission-message: You don't have <permission>
permissions:
    moddutydutch.modduty:
        description: Allows use of the command /modduty
        default: true 