name: ModDutyDutch
main: com.github.cmptrzd1592.ModDuty.ModDutyDutch
version: 1.0

commands:
    modduty:
        description: announces that the user is currently doing modreqs
        usage: /<command>
        permission: modonduty.modduty
        permission-message: You don't have <permission>
permissions:
    modonduty.*:
        description: gives access to all modduty commands
        children:
            modonduty.modduty: true
    modonduty.modduty:
        description: Allows use of the command /modduty
        default: not op        
